<?php

namespace srag\Plugins\Jitsi\ObjectSettings;

use ilJitsiPlugin;
use ilCheckboxInputGUI;
use ilObjJitsi;
use ilObjJitsiGUI;
use ilTextAreaInputGUI;
use ilTextInputGUI;
use srag\CustomInputGUIs\Jitsi\PropertyFormGUI\Items\Items;
use srag\CustomInputGUIs\Jitsi\PropertyFormGUI\PropertyFormGUI;

/**
 * Class ObjectSettingsFormGUI
 *
 * Generated by SrPluginGenerator v1.3.5
 *
 * @package srag\Plugins\Jitsi\ObjectSettings
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Core 1 <support-core1@studer-raimann.ch>
 */
class ObjectSettingsFormGUI extends PropertyFormGUI
{

    const PLUGIN_CLASS_NAME = ilJitsiPlugin::class;
    const LANG_MODULE = ilObjJitsiGUI::LANG_MODULE_SETTINGS;
    /**
     * @var ilObjJitsi
     */
    protected $object;


    /**
     * ObjectSettingsFormGUI constructor
     *
     * @param ilObjJitsiGUI $parent
     * @param ilObjJitsi    $object
     */
    public function __construct(ilObjJitsiGUI $parent, ilObjJitsi $object)
    {
        $this->object = $object;

        parent::__construct($parent, $object);
    }


    /**
     * @inheritDoc
     */
    protected function getValue(/*string*/ $key)
    {
        switch ($key) {
            case "description":
                return Items::getter($this->object, "long_description");

            default:
                return Items::getter($this->object, $key);
        }
    }


    /**
     * @inheritDoc
     */
    protected function initCommands()/*: void*/
    {
        $this->addCommandButton(ilObjJitsiGUI::CMD_SETTINGS_STORE, self::plugin()->translate("save", self::LANG_MODULE));

        $this->addCommandButton(ilObjJitsiGUI::CMD_SETTINGS, self::plugin()->translate("cancel", self::LANG_MODULE));
    }


    /**
     * @inheritDoc
     */
    protected function initFields()/*: void*/
    {
        $this->fields = [
            'title' => [
                self::PROPERTY_CLASS    => ilTextInputGUI::class,
                self::PROPERTY_REQUIRED => true
            ],
            'description' => [
                self::PROPERTY_CLASS    => ilTextAreaInputGUI::class,
                self::PROPERTY_REQUIRED => false
            ],
            'online' => [
                self::PROPERTY_CLASS => ilCheckboxInputGUI::class
            ]
        ];
    }


    /**
     * @inheritDoc
     */
    protected function initId()/*: void*/
    {

    }


    /**
     * @inheritDoc
     */
    protected function initTitle()/*: void*/
    {
        $this->setTitle(self::plugin()->translate('settings', self::LANG_MODULE));
    }


    /**
     * @inheritDoc
     */
    protected function storeValue(/*string*/ $key, $value)/*: void*/
    {
        switch ($key) {
            default:
                Items::setter($this->object, $key, $value);
                break;
        }
    }


    /**
     * @inheritDoc
     */
    public function storeForm() : bool
    {
        if (!parent::storeForm()) {
            return false;
        }

        $this->object->update();

        return true;
    }
}
