<?php

namespace srag\Plugins\Jitsi\Config;

use ilJitsiPlugin;
use srag\ActiveRecordConfig\Jitsi\Config\AbstractFactory;
use srag\ActiveRecordConfig\Jitsi\Config\AbstractRepository;
use srag\ActiveRecordConfig\Jitsi\Config\Config;
use srag\Plugins\Jitsi\Utils\JitsiTrait;

/**
 * Class Repository
 * Generated by SrPluginGenerator v1.3.5
 * @package srag\Plugins\Jitsi\Config
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author  studer + raimann ag - Team Core 1 <support-core1@studer-raimann.ch>
 */
final class Repository extends AbstractRepository
{

    use JitsiTrait;

    const PLUGIN_CLASS_NAME = ilJitsiPlugin::class;
    /**
     * @var self
     */
    protected static $instance = null;

    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }

    /**
     * Repository constructor
     */
    protected function __construct()
    {
        parent::__construct();
    }

    /**
     * @inheritDoc
     * @return Factory
     */
    public function factory() : AbstractFactory
    {
        return Factory::getInstance();
    }

    /**
     * @inheritDoc
     */
    protected function getTableName() : string
    {
        return ilJitsiPlugin::PLUGIN_ID . '_config';
    }

    /**
     * @inheritDoc
     */
    protected function getFields() : array
    {
        return [
            ConfigFormGUI::JITSI_URL       => Config::TYPE_STRING,
            ConfigFormGUI::OPEN_IN_NEW_TAB => Config::TYPE_BOOLEAN,
            //            ConfigFormGUI::LIST_TITLE => Config::TYPE_STRING,
        ];
    }
}
