<?php

namespace srag\Plugins\Jitsi\Utils;

use srag\Plugins\Jitsi\Repository;

/**
 * Trait JitsiTrait
 *
 * Generated by SrPluginGenerator v1.3.5
 *
 * @package srag\Plugins\Jitsi\Utils
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Core 1 <support-core1@studer-raimann.ch>
 */
trait JitsiTrait
{

    /**
     * @return Repository
     */
    protected static function jitsi() : Repository
    {
        return Repository::getInstance();
    }
}
